// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADhuafkjyDBjDNykC6k-3lxlOCxJpV6L8',
    appId: '1:119388237470:web:20b3215e2e8e03339a958f',
    messagingSenderId: '119388237470',
    projectId: 'foodmanager-d14b5',
    authDomain: 'foodmanager-d14b5.firebaseapp.com',
    storageBucket: 'foodmanager-d14b5.appspot.com',
    measurementId: 'G-QYXER49D9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8QLSVmpgO3GB_t6PLM2qBHUPzdIMIOI0',
    appId: '1:119388237470:android:95cf6cdee41493dc9a958f',
    messagingSenderId: '119388237470',
    projectId: 'foodmanager-d14b5',
    storageBucket: 'foodmanager-d14b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCEPASzfQH3SNFnv-zCpihWjKIGzpftFI',
    appId: '1:119388237470:ios:c11bc3d1388c23d69a958f',
    messagingSenderId: '119388237470',
    projectId: 'foodmanager-d14b5',
    storageBucket: 'foodmanager-d14b5.appspot.com',
    iosBundleId: 'com.example.foodManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCEPASzfQH3SNFnv-zCpihWjKIGzpftFI',
    appId: '1:119388237470:ios:c11bc3d1388c23d69a958f',
    messagingSenderId: '119388237470',
    projectId: 'foodmanager-d14b5',
    storageBucket: 'foodmanager-d14b5.appspot.com',
    iosBundleId: 'com.example.foodManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADhuafkjyDBjDNykC6k-3lxlOCxJpV6L8',
    appId: '1:119388237470:web:204630c44dda96199a958f',
    messagingSenderId: '119388237470',
    projectId: 'foodmanager-d14b5',
    authDomain: 'foodmanager-d14b5.firebaseapp.com',
    storageBucket: 'foodmanager-d14b5.appspot.com',
    measurementId: 'G-1CC92CV7F3',
  );
}
